In [ ]:
import pandas as pd
import importlib

In [ ]:
!git clone https://github.com/mgroovyank/electra.git

Cloning into 'electra'...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 366 (delta 67), reused 0 (delta 0), pack-reused 254
Receiving objects: 100% (366/366), 182.91 KiB | 859.00 KiB/s, done.
Resolving deltas: 100% (210/210), done.


In [ ]:
cd electra

/content/electra


In [ ]:
! mkdir ./data
! mkdir ./data/finetuning_data
! mkdir ./data/finetuning_data/sentimentclassification
! mkdir ./data/models

In [ ]:
!wget https://storage.googleapis.com/electra-data/electra_base.zip

--2020-06-18 16:12:47--  https://storage.googleapis.com/electra-data/electra_base.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 173.194.79.128, 2a00:1450:4013:c00::80
Connecting to storage.googleapis.com (storage.googleapis.com)|173.194.79.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 885890161 (845M) [application/zip]
Saving to: ‘electra_base.zip’

electra_base.zip    100%[===================>] 844.85M  51.0MB/s    in 17s     

2020-06-18 16:13:05 (50.0 MB/s) - ‘electra_base.zip’ saved [885890161/885890161]



In [ ]:
!unzip electra_base.zip

Archive:  electra_base.zip
   creating: electra_base/
  inflating: electra_base/electra_base.meta  
  inflating: electra_base/electra_base.index  
  inflating: electra_base/checkpoint  
  inflating: electra_base/vocab.txt  
  inflating: electra_base/electra_base.data-00000-of-00001  


In [ ]:
! mv  electra_base ./data/models

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
train = pd.read_csv("/content/drive/My Drive/fin-bank/train.tsv", sep="\t")
dev = pd.read_csv("/content/drive/My Drive/fin-bank/dev.tsv", sep="\t")
test = pd.read_csv("/content/drive/My Drive/fin-bank/test.tsv", sep="\t")

In [ ]:
train.to_csv("/content/electra/data/finetuning_data/sentimentclassification/train.csv", index=False, sep=",")
dev.to_csv("/content/electra/data/finetuning_data/sentimentclassification/dev.csv", index=False, sep=",")
test.to_csv("/content/electra/data/finetuning_data/sentimentclassification/test.csv", index=False, sep=",")

In [12]:
import tfelectra

In [13]:
importlib.reload(tfelectra)

<module 'tfelectra' from '/content/electra/tfelectra.py'>

In [14]:
configs = tfelectra.Configs(
    data_dir = "/content/electra/data",
    model_name =  "electra_base",
    model_size = "base",
    max_seq_length = 64,
    train_batch_size = 16,
    num_train_epochs = 3,
    label_list = ["0", "1", "2"],
    do_predict = True,
    do_eval = True
    )

In [18]:
electra_model = tfelectra.ElectraClassification(configs)

Config: model=electra_base, trial 1/1
data_dir /content/electra/data
debug False
do_eval True
do_lower_case True
do_train True
double_unordered True
embedding_size None
eval_batch_size 8
gcp_project None
init_checkpoint /content/electra/data/models/electra_base
iterations_per_loop 1000
keep_all_models True
layerwise_lr_decay 0.8
learning_rate 5e-05
log_examples False
max_seq_length 64
model_dir /content/electra/data/models/electra_base/finetuning_models/sentimentclassification_model
model_hparam_overrides {}
model_name electra_base
model_size base
n_writes_test 5
num_tpu_cores 1
num_train_epochs 3
num_trials 1
predict_batch_size 8
preprocessed_data_dir /content/electra/data/models/electra_base/finetuning_tfrecords/sentimentclassification_tfrecords
qa_eval_file <built-in method format of str object at 0x7f6d1ea038a0>
qa_na_file <built-in method format of str object at 0x7f6d1e9330c0>
qa_preds_file <built-in method format of str object at 0x7f6d1ea03d20>
raw_data_dir <built-in method for

In [19]:
electra_model.train()

Start training
Training for 582 steps
Building model...
Building complete
10/582 = 1.7%, SPS: 0.8, ELAP: 12, ETA: 11:45 - loss: 18.6964
20/582 = 3.4%, SPS: 1.2, ELAP: 16, ETA: 7:36 - loss: 13.3963
30/582 = 5.2%, SPS: 1.5, ELAP: 20, ETA: 6:10 - loss: 12.0788
40/582 = 6.9%, SPS: 1.7, ELAP: 24, ETA: 5:25 - loss: 15.0509
50/582 = 8.6%, SPS: 1.8, ELAP: 28, ETA: 4:57 - loss: 11.7278
60/582 = 10.3%, SPS: 1.9, ELAP: 32, ETA: 4:36 - loss: 8.4213
70/582 = 12.0%, SPS: 2.0, ELAP: 36, ETA: 4:21 - loss: 7.0620
80/582 = 13.7%, SPS: 2.0, ELAP: 40, ETA: 4:08 - loss: 2.7465
90/582 = 15.5%, SPS: 2.1, ELAP: 43, ETA: 3:57 - loss: 8.1572
100/582 = 17.2%, SPS: 2.1, ELAP: 47, ETA: 3:48 - loss: 9.1279
110/582 = 18.9%, SPS: 2.1, ELAP: 51, ETA: 3:40 - loss: 4.3011
120/582 = 20.6%, SPS: 2.2, ELAP: 55, ETA: 3:32 - loss: 4.4742
130/582 = 22.3%, SPS: 2.2, ELAP: 59, ETA: 3:25 - loss: 7.9544
140/582 = 24.1%, SPS: 2.2, ELAP: 1:03, ETA: 3:19 - loss: 5.7642
150/582 = 25.8%, SPS: 2.2, ELAP: 1:07, ETA: 3:12 - loss: 3.9380


In [20]:
y = electra_model.test()

Writing out predictions for [Task(sentimentclassification)] test
Loading dataset sentimentclassification_test
Existing tfrecords not found so creating
Writing example 0 of 970
Building model...
Building complete
Getting predictions for 970 sentimentclassification examples (test)


In [21]:
data = y

In [22]:
len(data)

970

In [26]:
y_pred = [np.argmax(data[d]) for d in data]

In [27]:
df_y = pd.read_csv("/content/electra/data/finetuning_data/sentimentclassification/test.csv", sep=",")
y = df_y["label"]

In [28]:
correct = np.sum(y == y_pred)
correct/len(y)

0.8824742268041237

In [29]:
report(y, y_pred)

[[107  16   1]
 [ 14 528  41]
 [  6  36 221]]
Accuracy: 0.882
Precision: 0.864
Recall: 0.870
F1-Score: 0.867


In [25]:
def report(y_true, y_pred):
  print(confusion_matrix(y_true, y_pred)) 
  print("Accuracy: {0:.3f}".format(accuracy_score(y_true, y_pred))) 
  print("Precision: {0:.3f}".format(precision_score(y_true, y_pred, average="macro")))
  print("Recall: {0:.3f}".format(recall_score(y_true, y_pred, average="macro")))
  print("F1-Score: {0:.3f}".format(f1_score(y_true, y_pred, average="macro")))

In [24]:
import numpy as np
import pandas as pd
import numpy as np
import pandas as pd
import sklearn
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle
