In [ ]:
import pandas as pd
import importlib

In [ ]:
!git clone https://github.com/mgroovyank/electra.git

Cloning into 'electra'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 375 (delta 0), reused 0 (delta 0), pack-reused 372
Receiving objects: 100% (375/375), 188.88 KiB | 920.00 KiB/s, done.
Resolving deltas: 100% (221/221), done.


In [ ]:
cd electra

/content/electra


In [ ]:
! mkdir ./data
#! mkdir ./data/finetuning_data
#! mkdir ./data/finetuning_data/sentimentclassification
#! mkdir ./data/models

In [ ]:
!wget https://storage.googleapis.com/electra-data/electra_small.zip

--2020-06-21 05:43:50--  https://storage.googleapis.com/electra-data/electra_small.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.166.128, 2a00:1450:400c:c02::80
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.166.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 171877176 (164M) [application/zip]
Saving to: ‘electra_small.zip’

electra_small.zip   100%[===================>] 163.91M  35.5MB/s    in 4.6s    

2020-06-21 05:43:55 (35.5 MB/s) - ‘electra_small.zip’ saved [171877176/171877176]



In [ ]:
!unzip electra_small.zip

Archive:  electra_small.zip
   creating: electra_small/
  inflating: electra_small/checkpoint  
  inflating: electra_small/electra_small.meta  
  inflating: electra_small/electra_small.data-00000-of-00001  
  inflating: electra_small/electra_small.index  
  inflating: electra_small/vocab.txt  


In [ ]:
#! mv  electra_small ./data/models

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
train = pd.read_csv("/content/drive/My Drive/fin-bank/train.tsv", sep="\t")
dev = pd.read_csv("/content/drive/My Drive/fin-bank/dev.tsv", sep="\t")
test = pd.read_csv("/content/drive/My Drive/fin-bank/test.tsv", sep="\t")

In [ ]:
train.to_csv("/content/electra/data/train.csv", index=False, sep=",")
dev.to_csv("/content/electra/data/dev.csv", index=False, sep=",")
test.to_csv("/content/electra/data/test.csv", index=False, sep=",")

In [ ]:
from tfelectra import Configs, ElectraClassification

In [ ]:
importlib.reload(tfelectra)

<module 'tfelectra' from '/content/electra/tfelectra.py'>

In [ ]:
#data_dir = where train, test files are present
#vocab_file = vocab.txt
#init_checkpoint = where initial checkpoint model is present
#output_dir = #where tf records are stores or preprocessed_data_dir
#model_dir = where checkpoint model is saved
configs = Configs(
    data_dir = "/content/electra/data",
    vocab_file = "/content/electra/electra_small/vocab.txt",
    init_checkpoint = "/content/electra/electra_small",
    output_dir = "/content/electra/model",
    model_name =  "electra_small",
    model_size = "small",
    max_seq_length = 64,
    train_batch_size = 16,
    num_train_epochs = 3,
    label_list = ["0", "1", "2"],
    do_predict = True,
    do_eval = True
    )

In [ ]:
electra_model = ElectraClassification(configs)

Config: model=electra_small, trial 1/1
data_dir /content/electra/data
debug False
do_eval True
do_lower_case True
do_train True
double_unordered True
embedding_size 128
eval_batch_size 8
gcp_project None
init_checkpoint /content/electra/electra_small
iterations_per_loop 1000
keep_all_models True
layerwise_lr_decay 0.8
learning_rate 5e-05
log_examples False
max_seq_length 64
model_dir /content/electra/model
model_hparam_overrides {}
model_name electra_small
model_size small
n_writes_test 5
num_tpu_cores 1
num_train_epochs 3
num_trials 1
predict_batch_size 8
preprocessed_data_dir /content/electra/model
raw_data_dir /content/electra/data
save_checkpoints_steps 1000000
task_names ['sentimentclassification']
tasks {'sentimentclassification': {'type': 'classification', 'labels': ['0', '1', '2'], 'header': True, 'text_column': 1, 'label_column': 2}}
tpu_job_name None
tpu_name None
tpu_zone None
train_batch_size 16
use_tfrecords_if_existing True
use_tpu False
vocab_file /content/electra/electr

In [ ]:
electra_model.train()

Start training
Training for 582 steps
Building model...
Building complete
10/582 = 1.7%, SPS: 0.8, ELAP: 12, ETA: 11:54 - loss: 19.4538
20/582 = 3.4%, SPS: 1.4, ELAP: 14, ETA: 6:30 - loss: 14.8972
30/582 = 5.2%, SPS: 2.0, ELAP: 15, ETA: 4:41 - loss: 17.3461
40/582 = 6.9%, SPS: 2.4, ELAP: 17, ETA: 3:46 - loss: 19.3486
50/582 = 8.6%, SPS: 2.8, ELAP: 18, ETA: 3:12 - loss: 14.0443
60/582 = 10.3%, SPS: 3.1, ELAP: 19, ETA: 2:49 - loss: 8.9134
70/582 = 12.0%, SPS: 3.4, ELAP: 21, ETA: 2:32 - loss: 16.4571
80/582 = 13.7%, SPS: 3.6, ELAP: 22, ETA: 2:19 - loss: 12.9261
90/582 = 15.5%, SPS: 3.8, ELAP: 24, ETA: 2:09 - loss: 13.6367
100/582 = 17.2%, SPS: 4.0, ELAP: 25, ETA: 2:00 - loss: 16.5410
110/582 = 18.9%, SPS: 4.2, ELAP: 26, ETA: 1:53 - loss: 8.7434
120/582 = 20.6%, SPS: 4.3, ELAP: 28, ETA: 1:47 - loss: 6.5155
130/582 = 22.3%, SPS: 4.5, ELAP: 29, ETA: 1:41 - loss: 14.3742
140/582 = 24.1%, SPS: 4.6, ELAP: 31, ETA: 1:36 - loss: 9.4169
150/582 = 25.8%, SPS: 4.7, ELAP: 32, ETA: 1:32 - loss: 11.044

In [ ]:
y = electra_model.test()

Writing out predictions for [Task(sentimentclassification)] test
Loading dataset sentimentclassification_test
Existing tfrecords not found so creating
Writing example 0 of 970
Building model...
Building complete
Getting predictions for 970 sentimentclassification examples (test)


In [ ]:
data = y

In [ ]:
len(data)

970

In [ ]:
y_pred = [np.argmax(data[d]) for d in data]

In [ ]:
df_y = pd.read_csv("/content/electra/data/test.csv", sep=",")
y = df_y["label"]

In [ ]:
correct = np.sum(y == y_pred)
correct/len(y)

0.8371134020618557

In [ ]:
report(y, y_pred)

[[ 91  22  11]
 [ 17 500  66]
 [ 11  31 221]]
Accuracy: 0.837
Precision: 0.803
Recall: 0.811
F1-Score: 0.806


In [ ]:
def report(y_true, y_pred):
  print(confusion_matrix(y_true, y_pred)) 
  print("Accuracy: {0:.3f}".format(accuracy_score(y_true, y_pred))) 
  print("Precision: {0:.3f}".format(precision_score(y_true, y_pred, average="macro")))
  print("Recall: {0:.3f}".format(recall_score(y_true, y_pred, average="macro")))
  print("F1-Score: {0:.3f}".format(f1_score(y_true, y_pred, average="macro")))

In [ ]:
import numpy as np
import pandas as pd
import numpy as np
import pandas as pd
import sklearn
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle
